fix

diff --git a/pipelines/al-help-pipemenu b/pipelines/al-help-pipemenu
--- a/pipelines/al-help-pipemenu
+++ b/pipelines/al-help-pipemenu
@@ -1,80 +1,118 @@
-#!/usr/bin/env bash
+#!/bin/bash
+#    al-help-pipemenu - an Openbox pipemenu for displaying help files
+#    Copyright (C) 2015 damo    <damo@bunsenlabs.org>
+#    Borrowed with love by the ArchLabs Boys.
+#
+#    This program is free software: you can redistribute it and/or modify
+#    it under the terms of the GNU General Public License as published by
+#    the Free Software Foundation, either version 3 of the License, or
+#    (at your option) any later version.
+#
+#    This program is distributed in the hope that it will be useful,
+#    but WITHOUT ANY WARRANTY; without even the implied warranty of
+#    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
+#    GNU General Public License for more details.
+#
+#    You should have received a copy of the GNU General Public License
+#    along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
-# al-help-pipemenu - an Openbox pipemenu for displaying help files
+#	Renamed for ARCHLabs
 
-readonly HELP='
-al-help-pipemenu an Openbox Pipe Menu for displaying help files
-It should normally be called from an openbox menu.
+HELP='    al-help-pipemenu an Openbox Pipe Menu for displaying help files
+    It should normally be called from an openbox menu.
 
 Options (usually passed from the menu):
     -h --help   show this message
 
-If al-help-pipemenu is called with no options (the usual method),
-it will output an xml openbox pipemenu displaying various help links,
+    If al-help-pipemenu is called with no options (the usual method),
+    it will output an xml openbox pipemenu displaying various help files,
+    both online and on the system.
 '
-for i in "$@"; do
+# look for a help option somewhere
+for i in "$@"
+do
     case "$i" in
-        -h|--help) echo "$HELP" ; exit 0
+    -h|--help)
+        echo "$HELP"
+        exit 0
+        ;;
     esac
 done
 
-if ! . "/usr/lib/archlabs/common/al-include.cfg" 2>/dev/null; then
-    echo $"Error: Failed to source /usr/lib/archlabs/common/al-include.cfg" >&2 ; exit 1
+BL_COMMON_LIBDIR='/usr/lib/archlabs/common'
+
+if ! . "$BL_COMMON_LIBDIR/al-include.cfg" 2> /dev/null; then
+    echo $"Error: Failed to source al-include.cfg in $BL_COMMON_LIBDIR" >&2
+    exit 1
 fi
 
 menuStart
-menuSeparator 'ARCHLABS LINUX ONLINE'
-menuItem 'ArchLabs Homepage' 'exo-open "https://www.archlabslinux.com/"'
-menuItem 'ArchLabs Reddit' 'exo-open "https://www.reddit.com/r/ArchLabsLinux/"'
-menuItem 'ArchLabs Forum' 'exo-open "https://forum.archlabslinux.com/"'
-menuItem 'ArchLabs Google+' 'exo-open "https://plus.google.com/u/0/communities/111177505820810068511"'
-menuItem 'ArchLabs Knowledge Base' 'exo-open "https://archlabs-knowledge-base.gitbooks.io/knowledge_base/content/"'
+menuSeparator 'Arch Linux'
+menuSeparator
+menuItem 'Arch Linux Homepage' 'xdg-open "https://www.archlinux.org/"'
+menuItem 'Arch Linux Wiki' 'xdg-open "https://wiki.archlinux.org/"'
+menuItem 'Arch Linux Reddit' 'xdg-open "https://www.reddit.com/r/archlinux/"'
+menuItem 'Arch Linux Forums' 'xdg-open "https://bbs.archlinux.org/"'
 
-menuSeparator 'ARCHLABS LINUX HELP'
-menuItem 'Forum Basic Help & Support' 'exo-open "https://forum.archlabslinux.com/c/newbie-corner"'
-menuItem 'Scripts, Tutorials & Tips' 'exo-open "https://forum.archlabslinux.com/c/configs-scripts-tutorials-tips"'
+menuSeparator 'Personalization'
+# menuSeparator
+# menuItem 'Forum Basic Help & Support' 'xdg-open "http://archlabs.prophpbb.com/forum7.html"'
+# menuItem 'Scripts, Tutorials & Tips' 'xdg-open "https://bbs.archlinux.org/viewforum.php?id=33"'
 
-menuSeparator 'GUIDES'
+menuSeparator
 
 menuSubmenu 'OpenboxWWW' 'Openbox'
-menuItem 'Openbox Homepage' 'exo-open "http://openbox.org/"'
-menuItem 'Openbox Getting Started' 'exo-open "http://openbox.org/wiki/Help:Getting_started"'
-menuItem 'Openbox Documentation' 'exo-open "http://openbox.org/wiki/Help:Contents"'
-menuItem 'Openbox FAQs' 'exo-open "http://openbox.org/wiki/Help:FAQ"'
-menuItem 'Arch Wiki Openbox Guide' 'exo-open "http://wiki.archlinux.org/index.php/Openbox"'
-menuItem 'Debian Wiki Openbox Guide' 'exo-open "https://wiki.debian.org/Openbox"'
-menuItem 'Urukramas Openbox Guide' 'exo-open "https://urukrama.wordpress.com/openbox-faq/"'
-menuItem 'Openbox Reddit' 'exo-open "https://www.reddit.com/r/openbox/"'
+menuSubmenu 'ObWWW' 'Openbox Website'
+menuItem 'Openbox Homepage' 'xdg-open "http://openbox.org/"'
+menuItem 'Openbox Getting Started' 'xdg-open "http://openbox.org/wiki/Help:Getting_started"'
+menuItem 'Openbox Documentation' 'xdg-open "http://openbox.org/wiki/Help:Contents"'
+menuItem 'Openbox FAQs' 'xdg-open "http://openbox.org/wiki/Help:FAQ"'
+menuSubmenuEnd
+menuItem 'Arch Wiki Openbox Guide' 'xdg-open "http://wiki.archlinux.org/index.php/Openbox"'
+menuItem 'Debian Wiki Openbox Guide' 'xdg-open "https://wiki.debian.org/Openbox"'
+menuItem 'Urukramas Openbox Guide' 'xdg-open "https://urukrama.wordpress.com/openbox-faq/"'
+menuItem 'Openbox Reddit' 'xdg-open "https://www.reddit.com/r/openbox/"'
 menuSubmenuEnd
 
 menuSubmenu 'Tint2WWW' 'Tint2'
-menuItem 'Tint2 Wiki: FAQ' 'exo-open "https://gitlab.com/o9000/tint2/wikis/FAQ"'
-menuItem 'Tint2 Wiki: Configuration' 'exo-open "https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md"'
-menuItem 'Tint2 Forum Thread' 'exo-open "https://forums.bunsenlabs.org/viewtopic.php?id=254"'
-menuSubmenuEnd
-
-menuSubmenu 'PolybarWWW' 'Polybar'
-menuItem 'Polybar GitHub' 'exo-open "https://github.com/jaagr/polybar"'
-menuItem 'Polybar Wiki' 'exo-open "https://github.com/jaagr/polybar/wiki"'
-menuItem 'Polybar Inspiration' 'exo-open "https://www.reddit.com/r/unixporn/search?q=polybar&restrict_sr=on&sort=new&t=all"'
-menuSubmenuEnd
-
-menuSubmenu 'RofitWWW' 'Rofi'
-menuItem 'Rofi GitHub' 'exo-open "https://github.com/DaveDavenport/rofi"'
-menuItem 'Rofi Wiki' 'exo-open "https://github.com/DaveDavenport/rofi/wiki"'
-menuItem 'Rofi Inspiration' 'exo-open "https://www.reddit.com/r/unixporn/search?q=rofi&restrict_sr=on&sort=new&t=all"'
+menuItem 'Tint2 Wiki: FAQ' 'xdg-open "https://gitlab.com/o9000/tint2/wikis/FAQ"'
+menuItem 'Tint2 Wiki: Configuration' 'xdg-open "https://gitlab.com/o9000/tint2/blob/master/doc/tint2.md"'
+menuItem 'Tint2 Forum Thread' 'xdg-open "https://forums.bunsenlabs.org/viewtopic.php?id=254"'
+menuItem 'Tint2 Man Pages' 'termite -e "man tint2" -t "tint2 man page"'
 menuSubmenuEnd
 
 menuSubmenu 'ConkyWWW' 'Conky'
-menuItem 'Conky Wiki' 'exo-open "https://github.com/brndnmtthws/conky/wiki"'
-menuItem 'Conky Inspiration' 'exo-open "https://www.reddit.com/r/unixporn/search?q=conky&restrict_sr=on&sort=new&t=all"'
-menuItem 'Conky Archive' 'exo-open "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
-menuItem 'Conky Reddit' 'exo-open "https://www.reddit.com/r/conky/"'
+menuItem 'Conky Wiki' 'xdg-open "https://github.com/brndnmtthws/conky/wiki"'
+menuItem 'Conky Archive' 'xdg-open "http://crunchbang.org/forums/viewtopic.php?pid=371424"'
+menuItem 'Conky Reddit' 'xdg-open "https://www.reddit.com/r/conky/"'
+menuItem 'Conky Man Pages' 'termite -e "man conky"'
 menuSubmenuEnd
 
-menuSubmenu 'NeofetchWWW' 'Neofetch'
-menuItem 'Neofetch GitHub' 'exo-open "https://github.com/dylanaraps/neofetch"'
-menuItem 'Neofetch Wiki' 'exo-open "https://github.com/dylanaraps/neofetch/wiki"'
+menuSeparator
+
+menuSubmenu 'ThemesWWW' 'Theme Resources'
+menuItem 'UnixPorn' 'xdg-open "https://www.reddit.com/r/unixporn/"'
+menuItem 'Bunsenlabs on DeviantArt' 'xdg-open "http://bunsenlabs.deviantart.com/"'
+menuItem 'Eye Candy Linux DeviantArt' 'xdg-open "http://eye-candy-linux.deviantart.com/"'
+menuItem 'Box-Look.org' 'xdg-open "http://www.box-look.org"'
+menuItem 'Gnome-Look.org' 'xdg-open "http://gnome-look.org/"'
+menuItem 'Eye Candy Linux Google+' 'xdg-open "https://plus.google.com/u/0/communities/104794997718869399105"'
+menuItem 'nixers.net' 'xdg-open "http://nixers.net/"'
+menuItem 'dotshare.it' 'xdg-open "http://dotshare.it/"'
 menuSubmenuEnd
+
+menuSeparator 'Man Pages'
+menuSeparator
+menuItem 'Termite' 'termite -e "man termite" -t "termite man page"'
+menuItem 'Compositor' 'termite -e "man compton" -t "compositor man page"'
+menuItem 'Dmenu' 'termite -e "man dmenu" -t "dmenu man page"'
+menuItem 'Xrandr' 'termite -e "man xrandr" -t "xrandr man page"'
+menuItem 'Yad' 'termite -e "man yad" -t "yad man page"'
+
+menuSeparator 'Wikis'
+menuSeparator
+menuItem 'Arch Wiki' 'xdg-open "https://wiki.archlinux.org/index.php/Table_of_contents"'
+menuItem 'Termite' 'xdg-open "https://wiki.archlinux.org/index.php/termite"'
 
 menuEnd
+
